"""PDF generation from Markdown study materials."""

from pathlib import Path
from typing import Optional
import markdown
from weasyprint import HTML, CSS
from weasyprint.text.fonts import FontConfiguration

from .utils.logger import setup_logger

logger = setup_logger(__name__)


class PDFGenerator:
    """Generate styled PDFs from Markdown content."""
    
    # CSS styling for beautiful PDFs
    PDF_STYLE = """
    @page {
        size: A4;
        margin: 2cm;
    }
    
    body {
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif;
        line-height: 1.6;
        color: #1a1a1a;
        max-width: 800px;
        margin: 0 auto;
    }
    
    h1 {
        color: #000;
        font-size: 32px;
        font-weight: 700;
        margin-top: 0;
        margin-bottom: 20px;
        border-bottom: 3px solid #000;
        padding-bottom: 10px;
    }
    
    h2 {
        color: #222;
        font-size: 24px;
        font-weight: 600;
        margin-top: 30px;
        margin-bottom: 15px;
        border-bottom: 2px solid #ddd;
        padding-bottom: 8px;
    }
    
    h3 {
        color: #333;
        font-size: 18px;
        font-weight: 600;
        margin-top: 20px;
        margin-bottom: 10px;
    }
    
    p {
        margin-bottom: 12px;
        text-align: justify;
    }
    
    ul, ol {
        margin-left: 25px;
        margin-bottom: 15px;
    }
    
    li {
        margin-bottom: 8px;
    }
    
    strong {
        color: #000;
        font-weight: 600;
    }
    
    code {
        background-color: #f5f5f5;
        padding: 2px 6px;
        border-radius: 3px;
        font-family: 'Monaco', 'Courier New', monospace;
        font-size: 0.9em;
    }
    
    pre {
        background-color: #f8f8f8;
        border: 1px solid #ddd;
        border-radius: 5px;
        padding: 15px;
        overflow-x: auto;
        margin-bottom: 20px;
    }
    
    blockquote {
        border-left: 4px solid #ddd;
        padding-left: 20px;
        margin-left: 0;
        color: #666;
        font-style: italic;
    }
    
    .flashcard {
        background-color: #f9f9f9;
        border: 1px solid #e0e0e0;
        border-radius: 8px;
        padding: 15px;
        margin-bottom: 15px;
    }
    
    .question {
        background-color: #e8f4f8;
        border-left: 4px solid #0066cc;
        padding: 12px;
        margin-bottom: 15px;
        border-radius: 4px;
    }
    
    .header {
        text-align: center;
        margin-bottom: 40px;
        padding-bottom: 20px;
        border-bottom: 2px solid #000;
    }
    
    .footer {
        text-align: center;
        color: #888;
        font-size: 12px;
        margin-top: 50px;
        padding-top: 20px;
        border-top: 1px solid #ddd;
    }
    """
    
    @staticmethod
    def markdown_to_pdf(
        markdown_content: str,
        output_path: Path,
        title: str = "Study Material"
    ) -> bool:
        """
        Convert Markdown content to styled PDF.
        
        Args:
            markdown_content: Markdown text
            output_path: Where to save PDF
            title: Document title
        
        Returns:
            True if successful
        """
        try:
            logger.info(f"Generating PDF: {output_path.name}")
            
            # Convert Markdown to HTML
            html_content = markdown.markdown(
                markdown_content,
                extensions=['extra', 'codehilite', 'tables']
            )
            
            # Wrap in full HTML document
            full_html = f"""
            <!DOCTYPE html>
            <html>
            <head>
                <meta charset="utf-8">
                <title>{title}</title>
            </head>
            <body>
                <div class="header">
                    <h1>📚 {title}</h1>
                    <p style="color: #666;">Generated by NotePal</p>
                </div>
                {html_content}
                <div class="footer">
                    <p>Created with NotePal - AI-Powered Study Assistant</p>
                </div>
            </body>
            </html>
            """
            
            # Generate PDF with styling
            font_config = FontConfiguration()
            html = HTML(string=full_html)
            css = CSS(string=PDFGenerator.PDF_STYLE, font_config=font_config)
            
            html.write_pdf(output_path, stylesheets=[css], font_config=font_config)
            
            logger.info(f"PDF generated successfully: {output_path}")
            return True
            
        except Exception as e:
            logger.error(f"Failed to generate PDF: {e}")
            return False
